#:schema ./schema/rtx.json
dotenv = '.env'
[env]
FOO = "bar"
THIS_PROJECT = "{{config_root}}-{{env.PWD}}"

[tools]
nodejs = 'lts'
tiny = { version = "1", foo = "bar" }
golang = { version = "latest", foo = "bar" }
python = { version = "latest", virtualenv = "$HOME/.cache/venv" }

[plugins]
nodejs = 'https://github.com/jdxcode/rtx-nodejs'

[alias.tiny]
abc = '1'

[settings]
plugin_autoupdate_last_check_duration = '10 seconds'
